### PR TITLE
Added a script to create the PlatformUIAssetsBundle release

### PR DESCRIPTION
**Pull request by dpobel**
# Description

Adds a script to create the PlatformUIAssetsBundle releases. This script also fixes [EZP-24661](https://jira.ez.no/browse/EZP-24661) by removing the API docs, the guides and the tests from YUI. This will allow to decrease the size of PlatformUIAssetBundle from 262Mb to 73Mb (!)

### CODE REVIEW

**Comment by andrerom** [comment]
I learned a few new shells things here :)

Only thing I can see is that it should probably check that commands it uses is installed (git and bower).
Otherwise +1

**Comment by dpobel** [comment]
updated with the git and bower checks
ping @yannickroger @mhyndle @andrerom

**Comment by andrerom** [comment]
+1

**Comment by mhyndle** [comment]
+1

**Pull request merged**
