### PR TITLE
EZP-24037: Add vectorized flags bundle to eZPlatformUIAssetsBundle

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZP-24037

### CODE REVIEW

**Comment by clash82** [comment]
@dpobel I should commit `bower.js` with or without Resources ?

**Comment by andrerom** [comment]
We specifically do not want the Resources in the git history, so we generate them when tagging so they are only part of tags.

if you check the diff, you can see you add a lot of stuff (over 6000 files), while only change here should be the meta files to make sure it is generated in dev and for tags.

**Comment by clash82** [comment]
@andrerom fixed, only meta data now.

**Comment by andrerom** [comment]
@dpobel would it be possible to trim/strip size of the tag btw? a lot of stuff in YUI we don't need usually.

**Pull request merged**
