### PR TITLE
EZP-25725: Upgraded AlloyEditor to 1.2.3

### PR DESCRIPTION
**Pull request by dpobel**
See https://github.com/ezsystems/PlatformUIBundle/pull/639

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by andrerom** [comment]
Merging to get on newer version before we start to tackle future copy/paste and formatting issues, will tag 3.0.0-alpha1 and adjust and rebase Platform UI PR to see if it gets green.

**Comment by sunpietro** [comment]
@andrerom this update breaks Studio Demo installation

**Comment by andrerom** [comment]
@sunpietro how so? you pull in 3.x or 2.x of asset bundle?

**Pull request merged**
